# Generated by Django 5.2.17 on 2026-09-28 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rejalashtirilgan mato (kg)')),
                ('actual_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amaldagi mato (kg)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fabric')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=100, help_text='Ip nisbati (%)', max_digits=5)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.fabric', verbose_name='Chiqadigan mato')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='inventory.yarn', verbose_name='Ishlatiladigan ip')),
            ],
        ),
    ]
