# Generated by Django 5.2.17 on 2026-09-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_fabricdispatch_fabricincome_order_yarnincome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtmachi nomi'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='fabric',
            field=models.CharField(max_length=255, verbose_name='Mato nomi'),
        ),
    ]
