# Generated by Django 5.2.17 on 2026-09-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionorder_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtmachi nomi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='density_finish',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Gr/m2 Iplik bo'yi (Finish)"),
        ),
        migrations.AlterField(
            model_name='order',
            name='fabric_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mato nomi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='machine_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dastgoh turi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtma nomi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Xizmat/Sotish 1 kg narxi ($)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Buyurtma miqdori (kg)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_or_sale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat yoki Sotish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Buyurtma summasi ($)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Eni (Tup/Mayli/Acik)'),
        ),
    ]
