# Generated by Django 5.2.17 on 2026-09-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_order_client_name_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricdispatch',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtmachi nomi'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='density_finish',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Gr/m2 Iplik bo'yi (Finish)"),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Mato chiqim sanasi'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='fabric_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mato nomi'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='machine_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Qaysi dastgohda to'qilgan"),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='machine_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dastgoh turi'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='order_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtma nomi'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1 kg narxi ($)'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mato miqdori (kg)'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='roll_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rulon soni (dona)'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='service_or_sale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat yoki Sotish'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Jami narxi ($)'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='width_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Eni (Tup/Mayli/Acik)'),
        ),
        migrations.AlterField(
            model_name='fabricdispatch',
            name='yarn_lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ip loti'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtmachi nomi'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='density_finish',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Gr/m2 Iplik bo'yi (Finish)"),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='fabric_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mato nomi'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='income_date',
            field=models.DateField(blank=True, null=True, verbose_name='Mato kirim sanasi'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='machine_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Qaysi dastgohda to'qilgan"),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='machine_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dastgoh turi'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='order_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtma nomi'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1 kg narxi ($)'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mato miqdori (kg)'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Qabul qilib olgan mas'ul xodim"),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='roll_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rulon soni (dona)'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='service_or_sale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat yoki Sotish'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Jami narxi ($)'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='width_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Eni (Tup/Mayli/Acik)'),
        ),
        migrations.AlterField(
            model_name='fabricincome',
            name='yarn_lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ip loti'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='actual_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Amaldagi mato (kg)'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='fabric',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mato nomi'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='target_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Rejalashtirilgan mato (kg)'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='bag_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qop soni (dona)'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID raqami'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='income_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ip kelgan sana'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1 kg ip narxi ($)'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ip miqdori (kg)'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ipni qabul qilib olgan mas'ul"),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='service_or_sale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat yoki Sotish'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='supplier_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip kelgan korxona nomi'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Jami ip narxi ($)'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='yarn_lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ip loti'),
        ),
        migrations.AlterField(
            model_name='yarnincome',
            name='yarn_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip nomi'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='bag_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qop soni (dona)'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtmachi'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='fabric_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mato nomi'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID raqami'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Chiqim sanasi'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='machine_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qaysi dastgoh'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='order_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtma nomi'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Miqdori (kg)'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='service_or_sale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat yoki Sotish'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='yarn_lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ip loti'),
        ),
        migrations.AlterField(
            model_name='yarnissue',
            name='yarn_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip nomi'),
        ),
        migrations.AlterField(
            model_name='yarnrefundtoclient',
            name='bag_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qop soni'),
        ),
        migrations.AlterField(
            model_name='yarnrefundtoclient',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtmachi'),
        ),
        migrations.AlterField(
            model_name='yarnrefundtoclient',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID raqami'),
        ),
        migrations.AlterField(
            model_name='yarnrefundtoclient',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Miqdori (kg)'),
        ),
        migrations.AlterField(
            model_name='yarnrefundtoclient',
            name='refund_date',
            field=models.DateField(blank=True, null=True, verbose_name='Chiqim sanasi'),
        ),
        migrations.AlterField(
            model_name='yarnrefundtoclient',
            name='service_or_sale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat yoki Sotish'),
        ),
        migrations.AlterField(
            model_name='yarnrefundtoclient',
            name='yarn_lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ip loti'),
        ),
        migrations.AlterField(
            model_name='yarnrefundtoclient',
            name='yarn_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip nomi'),
        ),
        migrations.AlterField(
            model_name='yarnreturn',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtmachi'),
        ),
        migrations.AlterField(
            model_name='yarnreturn',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID raqami'),
        ),
        migrations.AlterField(
            model_name='yarnreturn',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Miqdori (kg)'),
        ),
        migrations.AlterField(
            model_name='yarnreturn',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qaytgan sanasi'),
        ),
        migrations.AlterField(
            model_name='yarnreturn',
            name='service_or_sale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat yoki Sotish'),
        ),
        migrations.AlterField(
            model_name='yarnreturn',
            name='yarn_lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ip loti'),
        ),
        migrations.AlterField(
            model_name='yarnreturn',
            name='yarn_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip nomi'),
        ),
    ]
